baseURL = 'https://amendokat.github.io/amendokat/'
languageCode = 'en-us'
title = 'AMENDOKAT'

enableEmoji = true

enableGitInfo = true

enableRobotsTXT = true

[taxonomies]
  tag = 'tags'
  category = 'categories'
  
[params]
  chickens = '/amendokat/images/chicken.webp'

[menus]
  [[menus.nav]]
  name = 'home'
  pageRef = '/'
  weight = 1

  [[menus.nav]]
  name = 'about me'
  pageRef = '/about_me'
  weight = 2

  [[menus.nav]]
  name = 'my work'
  pageRef = '/my_work'
  weight = 3

  [[menus.nav]]
  name = 'blog'
  pageRef = '/blog'
  weight = 4

  [[menus.nav]]
  name = 'posts'
  pageRef = '/posts'
  weight = 5

  [[menus.nav]]
  name = 'site'
  pageRef = '/site'
  weight = 6

  [[menus.footerlinks]]
  name = 'ko-fi'
  url = 'https://ko-fi.com/amendokat'
  weight = 1

  [[menus.footerlinks]]
  name = 'bluesky'
  url = 'https://bsky.app/profile/amendokat.bsky.social'
  weight = 3

  [[menus.footerlinks]]
  name = 'neocities'
  url = 'https://neocities.org/site/amendokat'
  weight = 2

  [[menus.footerlinks]]
  name = 'tumblr'
  url = 'https://www.tumblr.com/amendokat'
  weight = 4