baseURL = 'https://amendokat.github.io/'
languageCode = 'en-us'
title = 'AMENDOKAT'

enableEmoji = true

enableGitInfo = true

enableRobotsTXT = true

[markup]
  [markup.goldmark.renderHooks]
      [markup.goldmark.renderHooks.image]
        useEmbedded = 'fallback'
      [markup.goldmark.renderHooks.link]
        useEmbedded = 'fallback'

[taxonomies]
  art_tag = 'art_tags'
  blog_tag = 'blog_tags'

[menus]
  [[menus.nav]]
  name = 'home'
  pageRef = '/'
  weight = 1

  [[menus.nav]]
  name = 'about me'
  pageRef = '/about_me'
  weight = 2

  [[menus.nav]]
  name = 'art gallery'
  pageRef = '/art_gallery'
  weight = 3

  [[menus.nav]]
  name = 'blog'
  pageRef = '/blog'
  weight = 4

  [[menus.nav]]
  name = 'posts'
  pageRef = '/posts'
  weight = 5

  [[menus.nav]]
  name = 'links'
  pageRef = '/links'
  weight = 6

  [[menus.nav]]
  name = 'site'
  pageRef = '/site'
  weight = 7